apiVersion: v1
kind: ResourceQuota
metadata:
  name: pokeclone-quota
  namespace: pokeclone
spec:
  hard:
    pods: "8"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 8Gi