apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: pokeclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeclone-backend
  template:
    metadata:
      labels:
        app: pokeclone-backend
    spec:
      containers:
      - name: pokeclone-backend
        image: slamoureux/pokeclone-back-end:eks-rds
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: DJANGO_KEY
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: backend-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: DB_PASS
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "150m"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3