apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pokeclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeclone-frontend
  template:
    metadata:
      labels:
        app: pokeclone-frontend
    spec:
      containers:
      - name: frontend
        image: slamoureux/pokeclone-front-end:minikube
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
